import type { Metadata } from 'next';
import TravelJournal from '../../travel-journal';
import PhotoGallery from '../../photo-gallery';
import { Enquiry } from '../../experience-components';
import { navratriPhotos, navratriDays } from '../../navratri-data';
import './navratri.css';
export const metadata: Metadata = { title: 'Hódos × Navratri | Gujarat, 13–19 October 2026', description: 'Seven days through Gujarat, after dark. Garba nights, local food, fire-lit traditions and textile craft. 13–19 October 2026. ₹40,000 per person. 15 spots.' };
export default function NavratriPage(){return <main id="main-content" className="navratri-page">
<section className="trip-hero navratri-hero"><img src="/images/navratri/canopy.webp" alt="A canopy of colourful fabric and warm festival lights" fetchPriority="high"/><div className="trip-hero-shade"/><div className="trip-hero-copy"><a className="breadcrumb" href="/curated">Hódos Curated / Gujarat</a><p className="eyebrow">13–19 OCTOBER 2026 · 15 SPOTS ONLY</p><h1>Hódos ×<br/><em>Navratri.</em></h1><p>A journey through Gujarat,<br/>after dark.</p><div className="trip-actions"><a className="button" href="#journal">Step into the festival</a><a className="text-link" href="/itineraries/hodos-navratri.pdf" download>Download itinerary</a></div></div><div className="trip-facts"><div><span>THE JOURNEY</span><strong>Seven days</strong></div><div><span>THE SETTING</span><strong>Four cities</strong></div><div><span>THE CIRCLE</span><strong>15 spots</strong></div><div><span>PER PERSON</span><strong>₹40,000</strong></div></div></section>
<section className="visual-intro section"><div><p className="eyebrow">STEP INTO THE FESTIVAL</p><h2>You don’t just watch.<br/><em>You belong to the rhythm.</em></h2></div><div><p>Local food. Garba nights. Fire-lit traditions.<br/>Seven days through the people, places and rituals that make Gujarat come alive.</p><a className="text-link" href="#itinerary">Explore the seven days</a></div></section>
<section className="trip-photo-strip"><PhotoGallery photos={[navratriPhotos[1],navratriPhotos[2],navratriPhotos[3]]} label="A first glimpse of Navratri"/></section>
<div className="navratri-route" aria-label="Journey route"><span>SURAT</span><i>/</i><span>VADODARA</span><i>/</i><span>AHMEDABAD</span><i>/</i><span>JAMNAGAR</span><i>/</i><span>AHMEDABAD</span></div>
<TravelJournal destination="Navratri" slug="navratri" volume="02" description="A festival in seven spreads. Turn the pages, follow the feeling." note="A visual moodboard using the supplied festival photographs. Images illustrate the atmosphere; they do not identify confirmed venues or performers."/>
<section className="navratri-mosaic section"><div className="section-heading"><div><p className="eyebrow">COLOUR. COMPANY. ONE MORE SONG.</p><h2>Nights you’ll<br/><em>carry home.</em></h2></div><p>Tap a frame. Stay a little longer.</p></div><PhotoGallery photos={navratriPhotos.slice(4)} label="Navratri festival photo collection"/></section>
<section className="trip-itinerary section" id="itinerary"><div className="section-heading"><div><p className="eyebrow">13–19 OCTOBER / THE JOURNEY</p><h2>Seven days.<br/><em>A thousand little moments.</em></h2></div><nav className="day-nav" aria-label="Itinerary days">{navratriDays.map(d=><a key={d.day} href={`#day-${d.day}`}>Day {d.day}</a>)}</nav></div>{navratriDays.map(d=><article className="trip-day" key={d.day} id={`day-${d.day}`}><div className="trip-day-heading"><span className="trip-day-number">{d.day}</span><div><p className="eyebrow">{d.date}</p><h3>{d.title}</h3></div></div><div className="trip-day-grid"><div className="trip-day-image"><img src={d.image} alt="Festival moodboard from the supplied Hódos Navratri collection" loading="lazy"/><span>THE FESTIVAL, IN FRAMES / GUJARAT</span></div><div className="trip-day-schedule">{d.items.map(([time,title,body])=><div className="schedule-row" key={title}><span>{time}</span><div><h4>{title}</h4><p>{body}</p></div></div>)}</div></div></article>)}</section>
<section className="navratri-fullbleed"><img src="/images/navratri/golden-night.webp" alt="Garba dancers beneath strings of golden festival lights" loading="lazy"/><div><p className="eyebrow">HÓDOS × NAVRATRI</p><h2>Find your people.<br/><em>Lose track of time.</em></h2></div></section>
<section className="trip-inclusions section"><div><p className="eyebrow">THE DETAILS, CONSIDERED</p><h2>A place<br/>in <em>the circle.</em></h2><p className="trip-price">₹40,000 <span>per person</span></p><p>15 spots · First come, first served.</p><a className="text-link" href="/itineraries/hodos-navratri.pdf" download>Keep the full itinerary</a></div><div><h3>What’s included</h3><dl className="inclusion-list"><div><dt>Stays</dt><dd>Accommodation in Surat, Vadodara, Ahmedabad and Jamnagar.</dd></div><div><dt>Festival nights</dt><dd>Yashvi Navratri, United Way or Laxmi Vilas Palace, the Aditya Gadhvi Garba Show, and Safed Parinda / an after-11:59 experience.</dd></div><div><dt>Local flavour</dt><dd>Tomato Puri breakfast at Dumas Beach, local Kathiyawadi food and a Surat local activity.</dd></div><div><dt>Living traditions</dt><dd>Mashal Raas and Athango Raas. A Patoda / Bandhani workshop is listed, subject to time.</dd></div><div><dt>If time permits</dt><dd>Surat Castle, Gavier Lake kayaking, textile markets, MSU, Maharaja Fateh Singh Museum, Manek Chowk, Kankaria Lake / Sabarmati Lake and a UNESCO heritage walk.</dd></div></dl><div className="not-included"><h4>Exclusions: to be confirmed</h4><p>The supplied itinerary leaves exclusions unconfirmed. Ask Hódos to confirm transport arrangements, meal coverage, final venues and exclusions before booking.</p></div></div></section>
<Enquiry title="So, you coming?" text="Ask about Hódos × Navratri, 13–19 October 2026. We’ll confirm availability and the final arrangements for your place in the circle."/>
<section className="collection-crosslink"><p>Another place. Another feeling.</p><a href="/curated">Explore all Curated journeys</a></section>
</main>}
