
import Atmosphere from './atmosphere';
import TripCarousel from './trip-carousel';
import { ExperienceCollection } from './experience-components';
import { experiences } from './experience-data';

export default function Home(){return <main id="main-content" className="home-page">
<section className="cinema-hero"><Atmosphere src="/images/hodos-courtyard.webp"/><div className="cinema-vignette"/><div className="cinema-copy"><p className="eyebrow">INDIA, BEYOND THE ORDINARY</p><h1 className="experiential-headline"><span>Discover</span><em>Experiential<br/>Travelling</em><span>with Hódos</span></h1><p className="cinema-subtitle">Follow a quieter path.<br/>Find a different kind of journey.</p><a className="scene-cta" href="#experiences">Step into the unfamiliar </a></div><div className="cinema-bottom"><span>01 / THE FIRST STEP</span><a href="#upcoming"><span className="scroll-track"/>SCROLL TO WANDER </a><span>A WORLD INSPIRED BY HAMPI</span></div></section>
<section className="upcoming-trips section" id="upcoming"><div className="section-heading"><div><p className="eyebrow">UPCOMING TRIPS / HÓDOS CURATED</p><h2>Your next <em>chapter.</em></h2></div><a className="text-link" href="/curated">Explore Curated </a></div><TripCarousel/></section>
<section id="experiences" className="home-experiences section"><div className="section-heading"><div><p className="eyebrow">HÓDOS ORIGINALS</p><h2>Not places.<br/><em>Moments.</em></h2></div><a className="text-link" href="/originals">Explore Originals </a></div><ExperienceCollection/></section>
<section className="hodos-visual-story" id="path"><div className="hodos-story-photo"><img src={experiences[2].image} alt="A quiet path under Coorg’s green canopy" loading="lazy"/><span>COORG, KARNATAKA / ROOM TO BREATHE</span></div><div className="hodos-story-copy"><p className="eyebrow">THE HÓDOS WAY</p><h2>You’ve been places.<br/>But have you been <em>moved?</em></h2><p>Quiet corners. Local perspectives.<br/>Moments you could never put on a checklist.</p><a className="text-link" href="/originals">Find your kind of elsewhere </a><div className="path-signature"><img className="signature-logo" src="/images/hodos-logo.png" alt="Hódos" width="150" height="43"/> <span>Greek for “the way”. An invitation to find yours.</span></div></div></section>
<section className="home-how section" id="how-it-works"><div className="section-heading"><div><p className="eyebrow">AN UNCOMPLICATED WAY TO GO</p><h2>Follow <em>the feeling.</em></h2></div></div><div className="how-grid"><article><span>01 / FIND</span><h3>Something speaks to you.</h3><p>Choose a moment or a whole journey.</p></article><article><span>02 / CONNECT</span><h3>One real conversation.</h3><p>Confirm the dates and details with Hódos.</p></article><article><span>03 / ARRIVE</span><h3>Bring your curiosity.</h3><p>Keep a little room for the unexpected.</p></article></div></section>
<section className="home-invitation"><img src="/images/hodos-courtyard.webp" alt="" loading="lazy"/><div><p className="eyebrow">THE WAY, LESS TAKEN</p><h2>The world still has<br/><em>something for you.</em></h2><a className="scene-cta" href="https://www.instagram.com/hodos.international/" target="_blank" rel="noopener noreferrer">Let’s find it </a></div></section>
</main>}
