export const spitiDays = [
 {day:1,route:'Chandigarh / Jibhi',title:'Leave the city behind.',distance:'Approx. 270 km · 8–9 hours',text:'Meet your tour captain in Chandigarh and follow the mountain roads into the green valleys around Jibhi.',highlights:['Scenic mountain drive','Explore Jibhi village','Evening bonfire and trip briefing'],meals:'Dinner',stay:'Jibhi'},
 {day:2,route:'Jibhi / Chitkul',title:'Follow the valley further.',distance:'Approx. 230 km · 8–9 hours',text:'Travel through Kinnaur towards Chitkul, with changing landscapes and time to explore the village.',highlights:['Jalori Pass','Sangla Valley','Baspa River views','Chitkul village exploration'],meals:'Breakfast & dinner',stay:'Chitkul'},
 {day:3,route:'Chitkul / Kalpa',title:'A morning without a rush.',distance:'Approx. 70 km · 3–4 hours',text:'Take a relaxed morning in Chitkul before continuing to Kalpa and the Kinner Kailash mountain views.',highlights:['Chitkul village walk','Local village temple','Baspa Bridge and riverfront','Suicide Point viewpoint','Kinner Kailash viewpoint'],meals:'Breakfast & dinner',stay:'Kalpa'},
 {day:4,route:'Kalpa / Tabo',title:'The landscape changes.',distance:'Approx. 160 km · 6–7 hours',text:'Enter Spiti through deep gorges and mountain villages. Stay for the quiet after dark.',highlights:['Nako village and Nako Lake','Ancient monasteries of Spiti','Tabo village exploration','Stargazing and night-sky photography'],meals:'Breakfast & dinner',stay:'Tabo'},
 {day:5,route:'Tabo / Dhankar / Kaza',title:'Old stories. Open skies.',distance:'Approx. 65 km · 3–4 hours',text:'Spend the day with Spiti’s cultural landmarks and valley views before arriving in Kaza.',highlights:['Tabo Monastery','Tabo meditation caves','Dhankar Monastery','Dhankar village and valley views'],meals:'Breakfast & dinner',stay:'Kaza'},
 {day:6,route:'Kaza villages / Losar',title:'Life, a little higher.',distance:'Approx. 65 km',text:'Explore high-altitude villages, monasteries and local cafés, then continue to Losar for the night.',highlights:['Hikkim post office','Komic village','Langza village and Buddha statue','Chicham Bridge','Key Monastery','Kibber village and wildlife sanctuary','High-altitude cafés and local experiences'],meals:'Breakfast & dinner',stay:'Losar'},
 {day:7,route:'Losar / Chandratal / Manali',title:'A lake worth the long road.',distance:'Approx. 140 km · 8–10 hours',text:'Start early for Chandratal Lake and a day crossing the rugged Himalayan landscape towards Manali.',highlights:['Kunzum Pass','Chandratal Lake','Batal','Chhatru','Gramphu','Atal Tunnel'],meals:'Breakfast',stay:'Manali'},
 {day:8,route:'Manali / Chandigarh',title:'Bring a little of it home.',distance:'Approx. 300 km · 8–9 hours',text:'After breakfast, return through Kullu Valley to Chandigarh, where the expedition concludes.',highlights:['Scenic drive through Kullu Valley','Arrival in Chandigarh','Tour concludes'],meals:'Breakfast',stay:null},
];
export const spitiPhotos=[
 {src:'/images/spiti/valley.webp',title:'Space to see differently',note:'Spiti Valley landscape. Destination photography, not a past Hódos departure.'},
 {src:'/images/spiti/monastery.webp',title:'Old stories in the mountains',note:'Monastery landscape in Spiti.'},
 {src:'/images/spiti/lake.webp',title:'The stillness of Chandratal',note:'Chandratal Lake, Himachal Pradesh.'},
];
