'use client';
import { useEffect, useRef, useState } from 'react';
import { Pause, Play } from 'lucide-react';
const trips=[
 {name:'Varkala',region:'KERALA, INDIA',line:'Waves, cliffs & a little chaos.',date:'18—20 SEPTEMBER 2026',route:'Bangalore / Varkala',facts:'3 days · ₹15,000 trip price',href:'/curated/varkala',images:['/images/varkala/dusk.webp','/images/varkala/surf.webp','/images/varkala/cafe.webp'],alts:['Palm-lined Varkala coast at dusk','Surfers on Varkala beach','Cliffside café overlooking the sea']},
 {name:'Spiti Valley',region:'HIMACHAL PRADESH, INDIA',line:'A little further. A world apart.',date:'DATES TO BE ANNOUNCED',route:'Chandigarh / Spiti / Chandigarh',facts:'8 days / 7 nights · 12 guests',href:'/curated/spiti',images:['/images/spiti/valley.webp','/images/spiti/monastery.webp','/images/spiti/lake.webp'],alts:['The mountain landscape of Spiti Valley','A monastery among Spiti’s mountains','Chandratal Lake in the Himalayas']}
];
export default function TripCarousel(){
 const [index,setIndex]=useState(0),[paused,setPaused]=useState(false),[hover,setHover]=useState(false),[focus,setFocus]=useState(false),[reduced,setReduced]=useState(true),[visible,setVisible]=useState(false),[hidden,setHidden]=useState(false),[progress,setProgress]=useState(0);const root=useRef<HTMLDivElement>(null),elapsed=useRef(0),startX=useRef<number|null>(null);
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const change=()=>setReduced(q.matches);change();q.addEventListener('change',change);const onVisibility=()=>setHidden(document.hidden);onVisibility();document.addEventListener('visibilitychange',onVisibility);const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.2});if(root.current)io.observe(root.current);return()=>{q.removeEventListener('change',change);document.removeEventListener('visibilitychange',onVisibility);io.disconnect();};},[]);
 const running=!paused&&!hover&&!focus&&!reduced&&visible&&!hidden;
 useEffect(()=>{if(!running)return;const timer=setInterval(()=>{elapsed.current+=100;if(elapsed.current>=7500){elapsed.current=0;setIndex(i=>(i+1)%trips.length);}setProgress(elapsed.current/7500);},100);return()=>clearInterval(timer);},[running]);
 const select=(i:number)=>{setIndex((i+trips.length)%trips.length);elapsed.current=0;setProgress(0);setPaused(true);};
 return <div ref={root} className={`trip-carousel ${running?'is-playing':''}`} role="region" aria-roledescription="carousel" aria-label="Upcoming Hódos trips" onMouseEnter={()=>setHover(true)} onMouseLeave={()=>setHover(false)} onFocusCapture={()=>setFocus(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocus(false);}} onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();select(index-1);}if(e.key==='ArrowRight'){e.preventDefault();select(index+1);}}}>
 <div className="trip-stage" onTouchStart={e=>{startX.current=e.touches[0].clientX;}} onTouchEnd={e=>{if(startX.current===null)return;const delta=e.changedTouches[0].clientX-startX.current;startX.current=null;if(Math.abs(delta)>55)select(index+(delta<0?1:-1));}}>
 {trips.map((trip,i)=><div key={trip.name} className={`trip-slide ${index===i?'active':''}`} inert={index!==i} aria-hidden={index!==i} role="group" aria-roledescription="slide" aria-label={`${i+1} of ${trips.length}: ${trip.name}`}><a className="upcoming-card" href={trip.href}><div className="upcoming-cover"><img src={trip.images[0]} alt={trip.alts[0]} loading="lazy"/><span className="upcoming-date">{trip.date}</span><div><span className="eyebrow">{trip.region}</span><h3>{trip.name}</h3><p>{trip.line}</p></div></div><div className="upcoming-side"><img src={trip.images[1]} alt={trip.alts[1]} loading="lazy"/><img src={trip.images[2]} alt={trip.alts[2]} loading="lazy"/></div><div className="upcoming-details"><span>{trip.route}</span><span>{trip.facts}</span><strong>Explore the trip </strong></div></a></div>)}
 </div>
 <div className="carousel-controls"><div className="trip-selectors">{trips.map((trip,i)=><button key={trip.name} onClick={()=>select(i)} aria-label={`Show ${trip.name}`} aria-pressed={i===index}><span>0{i+1}</span>{trip.name}<i><b style={{transform:`scaleX(${i===index?progress:0})`}}/></i></button>)}</div><div className="carousel-actions">{!reduced&&<button onClick={()=>setPaused(p=>!p)} aria-label={paused?'Resume automatic slides':'Pause automatic slides'} aria-pressed={paused}>{paused?<Play size={16}/>:<Pause size={16}/>}</button>}<button onClick={()=>select(index-1)} aria-label="Previous trip"><span>Previous</span></button><button onClick={()=>select(index+1)} aria-label="Next trip"><span>Next</span></button></div></div><span className="sr-only" aria-live={running?'off':'polite'}>{trips[index].name}, trip {index+1} of {trips.length}</span>
 </div>
}
