import type { Metadata } from 'next';
import PhotoGallery from '../photo-gallery';
import { varkalaPhotos } from '../varkala-photos';

import { Enquiry } from '../experience-components';
export const metadata: Metadata = { title: 'Hódos Curated | A thread of moments', description: 'Thoughtfully connected journeys from Hódos. Explore the Varkala coastal weekend and the eight-day Spiti Valley Expedition.' };
export default function CuratedPage() {
 return <main id="main-content" className="curated-page"><section className="curated-hero"><img src="/images/varkala-coast.webp" alt="Palm-lined Varkala coast at dusk" fetchPriority="high"/><div className="curated-hero-shade"/><div><p className="eyebrow">HÓDOS CURATED</p><h1>A journey.<br/>A thread of <em>moments.</em></h1><p>Every day connected. Every detail considered.<br/>Leave room for the things you cannot plan.</p><a className="button outline-button" href="#journeys">Explore the journeys </a></div><span className="curated-hero-note">MORE THAN A TRIP. A DIFFERENT RHYTHM.</span></section>
 <section className="curated-intro section"><p className="eyebrow">STAY LONGER. GO DEEPER.</p><h2>Good journeys<br/>have <em>a thread.</em></h2><p>The stays, the experiences, the time in between. Curated brings them together into a multi-day journey, so you can be present for the part that matters.</p></section>
 <section className="featured-journey section" id="journeys"><div className="section-heading"><div><p className="eyebrow">THE NEXT DEPARTURE</p><h2>The coast <em>is calling.</em></h2></div><span className="journey-date">18–20 SEPTEMBER 2026</span></div><a className="varkala-feature" href="/curated/varkala"><div className="varkala-feature-image"><img src="/images/varkala-surf.webp" alt="Surfers walking along the beach in Varkala" loading="lazy"/><span className="feature-badge">3 DAYS / KERALA</span></div><div className="varkala-feature-copy"><p className="eyebrow">BANGALORE / VARKALA</p><h3>Waves, cliffs<br/>& a little <em>chaos.</em></h3><p>Surf by day. Sunset by the cliff. Chaos by the pool. A coastal departure built around water, good food and good company.</p><dl><div><dt>The stay</dt><dd>Villa stay</dd></div><div><dt>The journey</dt><dd>Urbania transport</dd></div><div><dt>Trip price</dt><dd>₹15,000</dd></div></dl><span className="text-link">Explore the full journey </span></div></a></section>
 <section className="spiti-collection-card"><div className="section-heading"><div><p className="eyebrow">THE MOUNTAINS / DATES TO BE ANNOUNCED</p><h2>A world <em>apart.</em></h2></div></div><a className="varkala-feature" href="/curated/spiti"><div className="varkala-feature-image"><img src="/images/spiti/monastery.webp" alt="Key Monastery in the Spiti mountain landscape" loading="lazy"/><span className="feature-badge">8 DAYS / 7 NIGHTS</span></div><div className="varkala-feature-copy"><p className="eyebrow">CHANDIGARH / SPITI / CHANDIGARH</p><h3>Spiti Valley<br/><em>Expedition.</em></h3><p>Village mornings, ancient monasteries and the stillness of Chandratal.</p><dl><div><dt>The group</dt><dd>12 guests</dd></div><div><dt>The stay</dt><dd>Double / triple sharing</dd></div><div><dt>Dates & price</dt><dd>To be announced</dd></div></dl><span className="text-link">Explore the expedition </span></div></a></section>
 <section className="collection-photo-strip"><div className="section-heading"><div><p className="eyebrow">A FEW FRAMES FROM THE COAST</p><h2>Picture <em>yourself here.</em></h2></div><a className="text-link" href="/curated/varkala#journal">Open the Varkala journal </a></div><PhotoGallery photos={[varkalaPhotos[2],varkalaPhotos[3],varkalaPhotos[4]]}/></section>
 <Enquiry title="Come with a little curiosity." text="Ask us about Varkala or the Spiti Valley Expedition. We’ll confirm dates, availability and the final arrangements."/>
 <section className="collection-crosslink"><p>Just a morning? Just a moment?</p><a href="/originals">Explore Hódos Originals </a></section></main>;
}
