import type { Metadata } from 'next';

import { Enquiry } from '../../experience-components';
import PhotoGallery from '../../photo-gallery';
import { spitiDays, spitiPhotos } from '../../spiti-data';
export const metadata:Metadata={title:'Spiti Valley Expedition · 8 Days | Hódos Curated',description:'Eight days through Jibhi, Chitkul, Kalpa, Tabo, Kaza, Chandratal and Manali. A Hódos expedition for 12 guests, starting and ending in Chandigarh. Dates and price to be announced.'};
const chapters=[{label:'01 / THE APPROACH',title:'From green valleys…',image:'/images/spiti/village.webp',alt:'A winter mountain landscape at Chitkul',days:spitiDays.slice(0,2)},{label:'02 / A CHANGE OF SCENE',title:'…to another world.',image:'/images/spiti/valley.webp',alt:'The open mountain landscape of Spiti Valley',days:spitiDays.slice(2,4)},{label:'03 / THE HEART OF SPITI',title:'Stay with the stories.',image:'/images/spiti/monastery.webp',alt:'A monastery among the mountains of Spiti',days:spitiDays.slice(4,6)},{label:'04 / THE LONG WAY HOME',title:'One last kind of blue.',image:'/images/spiti/lake.webp',alt:'Chandratal Lake surrounded by mountains',days:spitiDays.slice(6,8)}];
export default function SpitiPage(){return <main id="main-content" className="spiti-page">
<section className="spiti-hero"><img src="/images/spiti/valley.webp" alt="The vast mountain landscape of Spiti Valley" fetchPriority="high"/><div className="spiti-shade"/><div className="spiti-hero-copy"><a className="breadcrumb" href="/curated">Hódos Curated / Himachal Pradesh</a><p className="eyebrow">8 DAYS / 7 NIGHTS · 12 GUESTS</p><h1>A little further.<br/><em>A world apart.</em></h1><p>Spiti Valley Expedition</p><a className="scene-cta" href="#journey">Follow the mountain road </a></div><div className="spiti-hero-footer"><span>CHANDIGARH / SPITI / CHANDIGARH</span><span>DATES & PRICE TO BE ANNOUNCED</span></div></section>
<section className="visual-intro section"><div><p className="eyebrow">THE HIMALAYAS, AT THEIR OWN PACE</p><h2>Less noise.<br/><em>More world.</em></h2></div><div><p>Village mornings. Ancient monasteries.<br/>Cold desert mountains. A lake like still glass.</p><a className="text-link" href="#enquire">Ask about this expedition </a></div></section>
<section className="collection-photo-strip"><PhotoGallery photos={spitiPhotos} label="Spiti Valley in photographs"/></section>
<section className="spiti-route section"><p className="eyebrow">THE CIRCUIT / EIGHT DAYS, UNFOLDING</p><div className="route-stops">{['Chandigarh','Jibhi','Sangla','Chitkul','Kalpa','Nako','Tabo','Dhankar','Kaza','Kibber','Hikkim','Komic','Langza','Losar','Chandratal','Manali','Chandigarh'].map((place,i)=><span key={`${place}-${i}`}><small>{String(i+1).padStart(2,'0')}</small>{place}</span>)}</div><p className="route-note">The circuit overview. Daily stops and overnight stays are detailed below.</p></section>
<section className="spiti-itinerary section" id="journey"><div className="section-heading"><div><p className="eyebrow">THE EXPEDITION</p><h2>Follow <em>the road.</em></h2></div><nav className="spiti-day-links" aria-label="Itinerary days">{spitiDays.map(d=><a key={d.day} href={`#spiti-day-${d.day}`}>{String(d.day).padStart(2,'0')}</a>)}</nav></div>{chapters.map(ch=><div className="spiti-chapter" key={ch.label}><div className="spiti-chapter-photo"><img src={ch.image} alt={ch.alt} loading="lazy"/><div><p className="eyebrow">{ch.label}</p><h3>{ch.title}</h3>{ch.label.startsWith('01')&&<small>Chitkul in winter · destination imagery</small>}</div></div><div className="spiti-chapter-days">{ch.days.map(d=><article id={`spiti-day-${d.day}`} key={d.day} className="spiti-day"><div className="spiti-day-number">{String(d.day).padStart(2,'0')}</div><div><p className="eyebrow">DAY {d.day} · {d.route}</p><h3>{d.title}</h3><span className="drive-time">{d.distance}</span><p>{d.text}</p><details open><summary>Along the way</summary><ul>{d.highlights.map(h=><li key={h}>{h}</li>)}</ul></details><div className="spiti-day-facts"><span><small>MEALS INCLUDED</small>{d.meals}</span><span><small>{d.stay?'OVERNIGHT':'FINISH'}</small>{d.stay||'Chandigarh'}</span></div></div></article>)}</div></div>)}</section>
<section className="trip-inclusions section"><div><p className="eyebrow">THE DETAILS, CONSIDERED</p><h2>A little clarity.<br/><em>Before you go.</em></h2><p>8 days / 7 nights · 12 guests</p><p className="trip-confirmation">Departure dates and package price are yet to be announced. Ask Hódos about availability and final arrangements.</p></div><div><h3>Included in the expedition</h3><dl className="inclusion-list"><div><dt>Accommodation</dt><dd>Seven nights on a double or triple sharing basis.</dd></div><div><dt>Meals</dt><dd>Breakfast and dinner as specified for each day. Day 1 includes dinner; Days 2–6 include breakfast and dinner; Days 7–8 include breakfast.</dd></div><div><dt>On the road</dt><dd>A comfortable vehicle for the entire tour, with an experienced driver / tour captain.</dd></div><div><dt>Experiences & support</dt><dd>Sightseeing as per the itinerary, a bonfire in Jibhi subject to weather, and assistance throughout the journey.</dd></div></dl><p className="trip-confirmation">Distances and drive times are approximate. Mountain roads, weather and access can affect the final sequence. Confirm the travel arrangements and any costs outside the listed inclusions with Hódos before booking.</p></div></section>
<Enquiry title="Let the mountains call." text="Ask Hódos about the Spiti Valley Expedition, departure dates, price and the final arrangements for your journey."/><section className="collection-crosslink"><p>Or follow the coast.</p><a href="/curated/varkala">Explore Varkala </a></section>
</main>}
