import type { Metadata } from 'next';
import TravelJournal from '../../travel-journal';
import PhotoGallery from '../../photo-gallery';
import { varkalaPhotos } from '../../varkala-photos';

import { Enquiry } from '../../experience-components';
export const metadata: Metadata = { title: 'Varkala · September Expedition | Hódos Curated', description: 'Waves, cliffs & a little chaos. A three-day Hódos journey from Bangalore to Varkala with surfing, kayaking, a villa stay and cliff sunsets. Trip price ₹15,000.' };
const days = [
 { day:'01', date:'DAY ONE', title:'The city falls away.', image:'/images/varkala-cliff.webp', alt:'The sea below the palm-lined cliff in Varkala', items:[['Departure','Bangalore to Varkala','Departure time to be confirmed.'],['3:00 PM','Arrive. Settle in.','Check in at the villa, freshen up and get ready to head out.'],['Before sunset','Meet the edge of the coast.','Varkala Cliff sunset walk, around 30 minutes before sunset. The stop depends on arrival time: Black Sand Beach, Varkala North Cliff or South Cliff.'],['9:00–10:00 PM onwards','A little poolside chaos.','Villa pool party. Drinks, music, games, pool and BBQ.']] },
 { day:'02', date:'DAY TWO', title:'Salt in your hair.', image:'/images/varkala-surf.webp', alt:'Surfers carrying their boards along Varkala beach', items:[['8:30–10:30 AM','Your first wave.','Surfing lessons at Black Beach with Nikhil from Moana Surf School. Learn the basics and get on the waves.'],['Lunch','Follow the group’s appetite.','Decided on the spot, based on the group’s preferences and the day’s plan.'],['4:30–6:30 PM','Back to the water.','Kayaking at Black Beach with Moana Surf School.'],['Around 8:00 PM','Dinner, facing the sea.','Wrap up the day over a beach-facing dinner.']] },
 { day:'03', date:'DAY THREE', title:'One more morning.', image:'/images/varkala-coast.webp', alt:'Varkala’s coastline and palms', items:[['9:00 AM','Breakfast, together.','One last breakfast and a final slow morning by the coast.'],['11:00 AM','The road home.','Check out and begin the return journey from Varkala.']] },
];
export default function VarkalaPage() {
 return <main id="main-content" className="varkala-page"><section className="trip-hero"><img src="/images/varkala-coast.webp" alt="The palm-lined coast of Varkala at dusk" fetchPriority="high"/><div className="trip-hero-shade"/><div className="trip-hero-copy"><a className="breadcrumb" href="/curated">Hódos Curated / Kerala</a><p className="eyebrow">September Expedition</p><h1>Waves, cliffs<br/>& a little <em>chaos.</em></h1><p>Surf by day. Sunset by the cliff.<br/>Chaos by the pool.</p><div className="trip-actions"><a className="button" href="#itinerary">Follow the journey </a><a className="text-link" href="/itineraries/hodos-varkala.pdf" download>Download itinerary </a></div></div><div className="trip-facts"><div><span>THE ROUTE</span><strong>Bangalore / Varkala</strong></div><div><span>THE TIME</span><strong>Three days</strong></div><div><span>THE STAY</span><strong>Villa stay</strong></div><div><span>TRIP PRICE</span><strong>₹15,000</strong></div></div></section>
 <section className="visual-intro section"><div><p className="eyebrow">THREE DAYS / ONE GOOD STORY</p><h2>Waves. Cliffs.<br/><em>Your kind of chaos.</em></h2></div><div><p>Surfing, kayaking, long dinners.<br/>A little planned. A little unexpected.</p><a className="text-link" href="#journal">Open the fieldnotes </a></div></section>
 <section className="trip-photo-strip"><PhotoGallery photos={[varkalaPhotos[0],varkalaPhotos[1],varkalaPhotos[3]]}/></section>
 <TravelJournal/>
 <section className="trip-itinerary section" id="itinerary"><div className="section-heading"><div><p className="eyebrow">THREE DAYS, UNFOLDING</p><h2>The shape of <em>the journey.</em></h2></div><nav className="day-nav" aria-label="Itinerary days">{days.map(d=><a key={d.day} href={`#day-${d.day}`}>Day {d.day}</a>)}</nav></div>{days.map(d=><article className="trip-day" key={d.day} id={`day-${d.day}`}><div className="trip-day-heading"><span className="trip-day-number">{d.day}</span><div><p className="eyebrow">{d.date}</p><h3>{d.title}</h3></div></div><div className="trip-day-grid"><div className="trip-day-image"><img src={d.image} alt={d.alt} loading="lazy"/><div className="day-photo-pair">{(d.day==='01'?[['sunset','Sunset along the cliff'],['pool','Poolside stay inspiration; final villa to be confirmed']]:d.day==='02'?[['paddle','Kayaks on the water'],['dinner','Dinner overlooking the sea']]:[['breakfast','A slow breakfast'],['souvenirs','Small keepsakes from Varkala']]).map(([file,alt])=><img key={file} src={`/images/varkala/${file}.webp`} alt={alt} loading="lazy"/>)}</div>{d.day==='01'&&<p className="gallery-disclaimer">Stay inspiration. Final villa to be confirmed.</p>}</div><div className="trip-day-schedule">{d.items.map(([time,title,body])=><div className="schedule-row" key={time}><span>{time}</span><div><h4>{title}</h4><p>{body}</p></div></div>)}{d.day==='02'&&<aside className="water-note"><strong>Before you get in</strong><p>Can’t swim, uncomfortable in water or scared of waves? Tell the Hódos team in advance.</p></aside>}</div></div></article>)}</section>
 <section className="trip-inclusions section"><div><p className="eyebrow">THE DETAILS, CONSIDERED</p><h2>Know before<br/>you <em>go.</em></h2><p className="trip-price">₹15,000 <span>Trip price</span></p><a className="text-link" href="/itineraries/hodos-varkala.pdf" download>Keep the itinerary </a></div><div><h3>What’s included</h3><dl className="inclusion-list"><div><dt>Stay & transport</dt><dd>Villa accommodation and Urbania transportation for the trip.</dd></div><div><dt>Experiences</dt><dd>Surfing lesson and kayaking at Black Beach, Varkala Cliff sunset walk, villa pool party and fun group activities.</dd></div><div><dt>Meals</dt><dd>Breakfast, lunch and dinner as per the final itinerary.</dd></div><div><dt>Beverages</dt><dd>Alcoholic and non-alcoholic beverages.</dd></div></dl><div className="not-included"><h4>Not included</h4><p>Extra activities and personal expenses.</p></div><p className="trip-confirmation">The departure time and final villa selection will be confirmed by the Hódos team. The first day’s beach stop depends on arrival time. Ask the team about current availability before making plans.</p></div></section>
 <Enquiry title="So, you coming?" text="Message @hodos.international about the Varkala September Expedition. We’ll confirm availability and talk through the details."/>
 <section className="collection-crosslink"><p>Follow another feeling.</p><a href="/originals">Discover the Originals collection </a></section></main>;
}
